name: Sample Workflow with Parameters

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'prod'
        type: choice
        options:
          - dev
          - stage
          - prod
      version:
        description: 'Version to deploy'
        required: true
        default: '1.0.0'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to environment
        run: |
          echo "Deploying to environment: ${{ github.event.inputs.environment }}"
          echo "Deploying version: ${{ github.event.inputs.version }}"
